module.exports = {
  ROLES: {
    SUPER_ADMIN: 'superAdmin',
    ADMIN: 'admin',
    DISPATCH_PLANNER: 'dispatchPlanner',
    SUPERVISOR: 'supervisor',
    PACK_OPERATOR: 'packOperator',
    PREPARATION_OPERATOR: 'prepOperator',
    PUTAWAY_OPERATOR: 'putawayOperator',
    PICKER: 'picker',
    WAREHOUSE_MANAGER: 'warehouseManager',
    DISPATCH_EXEC: 'dispatchExec',
    LOADING_SUPERVISOR: 'loadingSupervisor',
    STORES: 'stores',
    SECURITY: 'security'
  },
  PERMISSIONS: {
    PAINT_PLAN_MANAGE: 'PAINT_PLAN_MANAGE',
    PREPARATION_MANAGE: 'PREPARATION_MANAGE',
    WHEEL_QR_PRINT: 'WHEEL_QR_PRINT',
    PALLET_PACK: 'PALLET_PACK',
    PALLET_CLOSE: 'PALLET_CLOSE',
    PALLET_MERGE: 'PALLET_MERGE',
    PUTAWAY_EXECUTE: 'PUTAWAY_EXECUTE',
    INDENT_CREATE: 'INDENT_CREATE',
    PICKING_EXECUTE: 'PICKING_EXECUTE',
    LOADING_EXECUTE: 'LOADING_EXECUTE',
    GATEPASS_MANAGE: 'GATEPASS_MANAGE',
    GATE_OUT_VERIFY: 'GATE_OUT_VERIFY',
    RETURNABLES_MANAGE: 'RETURNABLES_MANAGE',
    TRACEABILITY_VIEW: 'TRACEABILITY_VIEW',
    REPORTS_VIEW: 'REPORTS_VIEW',
    MASTERS_MANAGE: 'MASTERS_MANAGE',
    QUALITY_HOLD_MANAGE: 'QUALITY_HOLD_MANAGE'
  },
  SERIES_PREFIXES: {
    FULL_PALLET: 'P',
    HALF_PALLET: 'H',
    MERGED_PALLET: 'M',
    RETURNABLE_ASSET: 'RP',
    PAINT_PLAN: 'PLN',
    INDENT: 'IND',
    PICK_LIST: 'PKL',
    LOADING: 'LD',
    GATE_PASS: 'GP'
  }
};
